CREATE TABLE DOCTORS(
	ID SERIAL NOT NULL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	CRM VARCHAR(6) NOT NULL UNIQUE,
	SPECIALITY VARCHAR(100) NOT NULL,
	PHONE VARCHAR(20) NOT NULL,
	STREET VARCHAR(100) NOT NULL,
	NEIGHBORHOOD VARCHAR(100) NOT NULL,
	ZIPCODE VARCHAR(9) NOT NULL,
	COMPLEMENT VARCHAR(100),
	ADDRESS_NUMBER VARCHAR(20),
	UF CHAR(2) NOT NULL,
	CITY VARCHAR(100) NOT NULL
);