CREATE TABLE PATIENTS(
	ID SERIAL NOT NULL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    DOCUMENT VARCHAR(14) NOT NULL UNIQUE,
    STREET VARCHAR(100) NOT NULL,
    NEIGHBORHOOD VARCHAR(100) NOT NULL,
    ZIPCODE VARCHAR(9) NOT NULL,
    COMPLEMENT VARCHAR(100),
    ADDRESS_NUMBER VARCHAR(20),
    UF char(2) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE
);